const messages = {
    triste: [
        "Sé que hoy no es el mejor día, pero recuerda que siempre tendrás mi amor para levantarte. Estoy aquí contigo, siempre.",
        "A veces el cielo se nubla, pero no olvides que las estrellas siempre brillan, y yo estaré ahí para ti.",
        "No importa lo que pase, mi cariño por ti nunca se apagará. ¡Ánimo, mi amor, que todo mejora!",
        "Tus días grises son solo una pausa, porque lo mejor está por llegar. Yo te amo y eso es todo lo que necesitas saber.",
        "En cada momento difícil, mi amor por ti se fortalece. Eres mi todo.",
        "Hoy no fue tu día, pero mañana será mejor, porque lo mejor de ti está por venir.",
        "La tristeza no dura para siempre, y yo estaré siempre a tu lado para hacerla desaparecer.",
        "A veces las lágrimas son solo la lluvia antes de que brille el sol. Yo soy tu sol.",
        "Te amo con todo mi corazón. Aunque hoy estés triste, siempre estaré aquí para apoyarte.",
        "Cada día que paso contigo, me doy cuenta de lo afortunado que soy. Y tú también lo eres.",
        "Mi amor por ti es más grande que cualquier tristeza. Juntos podemos con todo.",
        "Hoy es solo un día. Lo mejor está por venir. Te amo y te acompaño siempre.",
        "Quiero que sepas que aunque hoy te sientas triste, mi amor por ti nunca se va a apagar.",
        "La vida a veces es dura, pero contigo a mi lado sé que todo lo superamos.",
        "Tu tristeza no es para siempre, pero mi amor por ti sí lo es.",
        "Hoy estás triste, pero el amor que te tengo te ayudará a encontrar la felicidad.",
        "No importa lo que pase, hoy y siempre, te estoy enviando todo mi amor.",
        "Hoy no es el mejor día, pero siempre lo será porque te tengo a ti.",
        "Quiero que sepas que en cada momento triste, mi corazón está a tu lado, apoyándote.",
        "Recuerda que siempre estaré contigo, sin importar el estado de ánimo. Juntos podemos con todo.",
        "Sé que es difícil ahora, pero en este preciso momento, quiero que sepas que te amo más de lo que imaginas.",
        "Cada día contigo, incluso los difíciles, me hace amarte más. Juntos podemos con todo.",
        "Hoy es solo un día. Lo mejor está por venir. Te amo y te acompaño siempre.",
        "Quiero que sepas que aunque hoy te sientas triste, mi amor por ti nunca se va a apagar.",
        "La vida a veces es dura, pero contigo a mi lado sé que todo lo superamos.",
        "Tu tristeza no es para siempre, pero mi amor por ti sí lo es.",
        "Hoy estás triste, pero el amor que te tengo te ayudará a encontrar la felicidad.",
        "No importa lo que pase, hoy y siempre, te estoy enviando todo mi amor.",
        "Hoy no es el mejor día, pero siempre lo será porque te tengo a ti.",
        "Quiero que sepas que en cada momento triste, mi corazón está a tu lado, apoyándote."
    ],

    enojo: [
     "Sé que estás enojada, pero recuerda que lo importante es resolver las cosas con calma y amor.",
        "El enojo es solo una emoción pasajera. Lo que realmente importa es lo que sentimos el uno por el otro.",
        "Tómate un momento para respirar, el amor que nos tenemos puede superar cualquier enojo.",
        "Enojarse es normal, pero no olvides que siempre estaré aquí para escucharte y apoyarte.",
        "A veces necesitamos liberar el enojo para poder avanzar. Yo te apoyo en todo momento.",
        "Sé que ahora estás enojada, pero quiero que recuerdes lo maravillosa que eres y lo mucho que te quiero.",
        "El enojo no define nuestra relación, lo que importa es cómo lo manejamos. Y yo estaré aquí para ti.",
        "Es normal sentir enojo, pero siempre habrá espacio para el perdón y la comprensión entre nosotros.",
        "El enojo se va, pero el amor que siento por ti es constante y nunca cambiará.",
        "Tomémonos un respiro y recordemos que juntos podemos resolver cualquier desacuerdo.",
        "No dejes que el enojo nuble lo hermoso que tenemos. Estoy aquí para hablar cuando estés lista.",
        "A veces el enojo nos ayuda a entender lo que queremos, pero siempre debemos recordarnos cuánto nos amamos.",
        "Sé que ahora te sientes enojada, pero quiero que sepas que mi amor por ti es más grande que cualquier discusión.",
        "El enojo puede ser difícil, pero estoy seguro de que lo superaremos juntos, como siempre lo hemos hecho.",
        "No hay nada que no podamos resolver si seguimos comunicándonos con amor y respeto.",
        "Tómate tu tiempo para calmarte, siempre habrá tiempo para sanar y seguir adelante.",
        "Aunque ahora estés enojada, no olvides que estoy aquí para ti, hoy y siempre.",
        "El enojo es solo una respuesta, pero lo que realmente importa es cómo nos amamos.",
        "Recuerda que enojarse es normal, pero siempre podemos elegir el amor para sanar y avanzar.",
        "Lo importante es que siempre nos apoyemos, incluso cuando estamos en desacuerdo.",
        "Sé que las emociones son intensas, pero quiero que recuerdes que nada nos separará. Te amo.",
        "Lo que sentimos el uno por el otro es más grande que cualquier enojo. Estoy aquí para ti siempre.",
        "El enojo puede ser difícil, pero el amor lo hace todo más fácil. Juntos, podemos superar cualquier obstáculo.",
        "A veces las discusiones son necesarias para crecer. Estoy listo para hablar cuando tú lo estés.",
        "No dejes que el enojo te nuble, lo que importa es el amor y el respeto que tenemos el uno por el otro.",
        "Sé que ahora te sientes así, pero siempre hay espacio para la calma y la paz entre nosotros.",
        "No te preocupes por lo que te hizo enojar, lo importante es que sigamos avanzando juntos.",
        "El enojo es solo una fase. El amor que sentimos siempre perdura y nos da fuerzas para seguir adelante.",
        "Respira hondo, mi amor. Estoy aquí para escucharte y resolverlo juntos.",
        "No importa lo que haya pasado, lo importante es que nos tenemos el uno al otro para superar cualquier enojo."
    ],

    feliz: [
        "Estoy tan feliz de que estés aquí conmigo. Tu felicidad es mi felicidad.",
        "Cada día contigo es un motivo para sonreír. Eres la razón de mi alegría.",
        "Verte feliz me llena de una paz y una felicidad indescriptible. Me haces tan feliz.",
        "La felicidad no es un destino, es un viaje, y me encanta recorrerlo a tu lado.",
        "Estar contigo me hace sentir tan afortunado. Gracias por ser la luz en mi vida.",
        "Tu felicidad me llena el corazón de alegría. Me encanta verte sonreír.",
        "Cada momento contigo es un regalo, y mi corazón no puede dejar de sonreír.",
        "La felicidad está en las pequeñas cosas, y tú eres mi cosa más preciosa.",
        "Hoy me siento increíblemente feliz, porque tú estás a mi lado.",
        "Tu sonrisa ilumina mi mundo entero. Soy tan afortunado de tenerte.",
        "No hay nada más bonito que verte feliz. Tu alegría es mi mayor logro.",
        "Tu felicidad es el motor que mueve mi día. Gracias por ser quien eres.",
        "Siempre que estás feliz, mi corazón late más fuerte. Eres mi razón para ser feliz.",
        "Cuando estás feliz, el mundo parece un lugar mucho mejor. Gracias por compartir tu felicidad conmigo.",
        "No hay mejor lugar para estar que a tu lado, viendo cómo brillas de felicidad.",
        "Estoy tan feliz de poder compartir esta vida contigo. Eres mi mayor bendición.",
        "No puedo dejar de sonreír cuando te veo feliz. Eres la mejor parte de mi vida.",
        "Tu felicidad es mi mayor regalo, y siempre haré lo posible por hacerte feliz.",
        "Ver tu felicidad me hace sentir que todo lo que he hecho en mi vida ha valido la pena.",
        "Me haces sentir tan feliz simplemente por ser tú. Te amo más de lo que las palabras pueden expresar.",
        "Cada día que paso contigo es un recordatorio de lo afortunado que soy de tenerte en mi vida.",
        "Tu felicidad es todo lo que necesito para sentir que mi vida tiene sentido.",
        "Cuando te veo feliz, siento que el mundo es un lugar perfecto. Gracias por estar en mi vida.",
        "Hoy es un día especial, porque estamos juntos y porque estás feliz. Eso lo hace todo perfecto.",
        "Cada risa, cada mirada tuya llena mi vida de una alegría inmensa.",
        "Nunca dejes de ser feliz, porque tu felicidad es la que da sentido a mi vida.",
        "Es un privilegio verte feliz, y siempre haré lo que pueda para seguir viéndote sonreír.",
        "Tu felicidad es la chispa que enciende mi vida. No hay nada que me haga más feliz que verte bien.",
        "Me haces el ser más feliz del mundo con solo tu presencia. Eres mi felicidad.",
        "Estar a tu lado me hace sentir como si estuviera en el lugar más feliz del mundo.",
        "La felicidad no es solo un sentimiento, es un estilo de vida contigo."
    ],

    extraño: [
        "Cada segundo lejos de ti me parece una eternidad. Te extraño más de lo que las palabras pueden expresar.",
        "Te extraño tanto, pero sé que pronto estaremos juntos de nuevo y todo será aún más hermoso.",
        "Mi corazón te extraña, pero cada pensamiento de ti me da fuerzas para seguir adelante.",
        "No puedo esperar para verte de nuevo. Te extraño más de lo que crees.",
        "La distancia entre nosotros solo hace que mi amor por ti crezca aún más. Te extraño muchísimo.",
        "Cada día sin ti es un recordatorio de lo afortunado que soy de tenerte en mi vida.",
        "Te extraño con todo mi ser, pero cada día que pasa me acerca más al momento en que estaré a tu lado.",
        "El tiempo sin ti parece detenerse. Te extraño tanto y no veo la hora de volver a verte.",
        "El amor no conoce distancias. Te extraño, pero siempre te llevo en mi corazón.",
        "Te extraño más de lo que puedo poner en palabras, pero cada vez que pienso en ti, mi corazón se siente un poco más lleno.",
        "Aunque estemos lejos, siempre estás en mis pensamientos. Te extraño muchísimo.",
        "La distancia entre nosotros solo me hace apreciar aún más cada momento que pasamos juntos. Te extraño mucho.",
        "El tiempo sin ti es difícil, pero sé que la espera valdrá la pena. Te extraño tanto.",
        "Te extraño tanto que mi alma parece vacía sin ti. No puedo esperar para abrazarte de nuevo.",
        "El amor que siento por ti no entiende de distancias. Cada día que pasa me hace extrañarte más.",
        "Aunque estemos lejos físicamente, mi corazón siempre está contigo. Te extraño mucho.",
        "Te extraño más de lo que imaginé posible. Mi vida no es la misma sin ti a mi lado.",
        "La distancia solo me hace darme cuenta de lo mucho que te necesito en mi vida. Te extraño profundamente.",
        "Estar lejos de ti me hace valorar aún más lo increíble que eres. Te extraño muchísimo.",
        "Te extraño tanto, pero sé que pronto estaremos juntos y eso hace que la espera sea más llevadera.",
        "No importa cuántos kilómetros nos separen, siempre estarás en mi corazón. Te extraño muchísimo.",
        "Te extraño tanto que a veces siento que mi alma busca la tuya en cada rincón.",
        "Te extraño con cada fibra de mi ser. La espera será más dulce cuando esté a tu lado de nuevo.",
        "No sé cómo vivir sin verte todos los días, pero sé que cada día que pasa nos acerca más.",
        "Te extraño más de lo que las palabras pueden expresar. Mi vida no es la misma sin ti.",
        "Cada minuto sin ti parece eterno. Te extraño tanto, mi amor.",
        "Aunque no estés a mi lado, siempre siento que estamos juntos en espíritu. Te extraño muchísimo.",
        "Te extraño con todo mi corazón, pero sé que cada segundo que pasa es un paso más cerca de verte de nuevo.",
        "Mi vida está incompleta sin ti. Te extraño más de lo que imaginas."
    ],

    no_se: [
        "Está bien no saber cómo te sientes. Lo importante es que estoy aquí para ti, sin importar qué.",
        "No siempre tenemos que tener respuestas. Solo respira y recuerda que te amo muchísimo.",
        "A veces el corazón solo necesita un abrazo silencioso. Aquí tienes el mío, aunque sea virtual.",
        "No tienes que estar bien todo el tiempo. Yo te entiendo, y estoy a tu lado siempre.",
        "Sentirse así es totalmente válido. Quiero que sepas que puedes contar conmigo para todo.",
        "Hoy no sabes cómo estás, pero yo sí sé algo: eres lo más hermoso que tengo.",
        "Cuando no sepas qué sentir, solo recuerda cuánto te amo.",
        "No es necesario entenderlo todo ahora. Lo importante es que no estás sola.",
        "No saber cómo estás también es una forma de sentir. Te acompaño, con todo mi amor.",
        "Sea lo que sea que sientas, lo enfrentamos juntos. Estoy contigo.",
        "No necesitas fingir que todo está bien. Yo te acepto tal como eres, en todos tus estados.",
        "Si el mundo se siente confuso, mira nuestro amor, que es claro y verdadero.",
        "Tal vez no sepas cómo te sientes, pero yo sí sé que tú eres mi persona favorita.",
        "Es normal sentirse desorientada a veces. Lo bueno es que aquí estoy para sostenerte.",
        "Cuando no entiendas tus emociones, cierra los ojos y piensa en nosotros.",
        "Hoy quizás no sepas cómo estás, pero espero que sepas cuánto significas para mí.",
        "No tienes que tenerlo todo claro, porque tienes a alguien que te ama pase lo que pase.",
        "A veces solo necesitas escuchar esto: te amo, estoy contigo y todo estará bien.",
        "No saber cómo te sientes no te hace débil. Te hace humana. Y yo te admiro más por eso.",
        "Si no sabes cómo estás, yo te presto un poco de mi paz. Siempre para ti.",
        "Si hoy es un día raro, que sepas que incluso en esos días, eres mi sol.",
        "No importa cuán confusos sean tus pensamientos, mi amor por ti siempre será claro.",
        "Hoy no sabes cómo estás, pero yo sí sé que tú haces mi vida mejor cada día.",
        "Tu alma puede estar en pausa, pero mi amor por ti nunca se detiene.",
        "Si no sabes cómo estás, déjame ayudarte a encontrar un poquito de alegría.",
        "Hoy no tienes que ser fuerte. Solo tienes que ser tú, y eso es más que suficiente.",
        "Aunque no lo sepas ahora, estás haciendo lo mejor que puedes. Y eso vale muchísimo.",
        "Sentir que no sientes nada también es parte del proceso. Estoy aquí, sin juzgarte.",
        "No saber cómo estás no cambia el hecho de que eres profundamente amada.",
        "Tu confusión no es un problema, es parte del camino. Caminemos juntos, paso a paso."
    ],

    leer: [
        "Te amo más que a mi canción favorita en repeat. 💖",
        "Si estás leyendo esto, quiero que sepas que eres mi persona favorita en todo el universo.",
        "Hoy puede ser un día normal, pero tú lo haces especial solo con existir.",
        "¿Sabías que tu sonrisa puede mejorar mi peor día? Intenta sonreír ahora 😘",
        "Me encantaría darte un abrazo ahora mismo. Pero por ahora, recibe este mensaje lleno de amor.",
        "Entre todas las personas del mundo, tuve la suerte de enamorarme de ti.",
        "Eres como un rayito de sol que ilumina todo a su paso. Gracias por ser tú.",
        "A veces no necesitas razones para sonreír... solo recuerda que yo te amo.",
        "Cada día contigo es como una página nueva de mi historia favorita.",
        "Te pienso más veces de las que pestañeo. Y eso es muchísimo.",
        "Estar contigo es como vivir en una película romántica con final feliz asegurado.",
        "Tú eres la magia en mi día a día. No necesitas hacer nada, solo existir.",
        "Cuando pienso en cosas bonitas, tú eres la primera imagen que aparece.",
        "Eres tan especial que cada palabra se queda corta para describirte.",
        "Si pudiera escribirte una carta cada vez que pienso en ti, tendría una biblioteca entera.",
        "No olvides lo increíble que eres, incluso cuando no te sientas así.",
        "Te mando una dosis de cariño, sonrisas y abracitos virtuales. ❤️",
        "Cada vez que respiro, una parte de mi corazón dice tu nombre.",
        "No hay filtro que le gane a tu belleza natural. Y no hablo solo de lo físico.",
        "Si fueras un libro, no me cansaría de leerte una y otra vez.",
        "Estoy aquí, incluso cuando no lo digo, incluso cuando no lo ves.",
        "Tú me haces querer ser mejor persona, solo por merecerte.",
        "No importa lo que pase hoy: tú y yo somos más fuertes que cualquier cosa.",
        "Quisiera tomar tu mano ahora mismo y caminar juntos a donde sea.",
        "Tus abrazos son mi lugar favorito del mundo. Te extraño ahí.",
        "¿Ya te dije hoy que te amo? Bueno... te amo.",
        "Tienes una luz que ni los días nublados pueden apagar.",
        "Eres mi paz en medio del caos. Gracias por existir.",
        "Tú no eres mi mitad. Eres el todo que le da sentido a mi vida.",
        "Hoy, solo quería recordarte que para mí, tú lo eres todo."
    ],
    // (Agrega las frases para enojo, felicidad, etc., aquí)
};

function showMessage(feeling) {
    let messageContainer = document.getElementById('message');
    let randomIndex = Math.floor(Math.random() * messages[feeling].length);
    messageContainer.innerHTML = messages[feeling][randomIndex];
    messageContainer.style.display = "block";
}

// Asumiendo que ya pegaste todas las categorías completas
document.getElementById('emotion-select').addEventListener('change', function () {
    const emotion = this.value;
    if (emotion && messages[emotion]) {
      const frases = messages[emotion];
      const aleatoria = frases[Math.floor(Math.random() * frases.length)];
      document.getElementById('message-box').innerHTML = `<p>${aleatoria}</p>`;
    } else {
      document.getElementById('message-box').innerHTML = '';
    }
  });
  
